/**
 * @typedef {Object} PerformanceTimelineEntry - Represents a data point in the building's performance over time.
 * @property {number} year - The year for this timeline entry.
 * @property {number} projectedFloodLevel - The projected flood level for that year (in feet above datum).
 * @property {number} resilienceScoreAtYear - The building's calculated resilience score for that specific year.
 * @property {number} floodDepthInches - The projected depth of floodwater (in inches) above the lowest floor for that year (0 if not flooded).
 */

/**
 * @typedef {Object} CostBenefitAnalysis - Summary of financial aspects of flood resilience.
 * @property {number} upfrontCostEstimate - Estimated initial cost of implementing recommendations.
 * @property {number} longTermSavingsEstimate - Estimated long-term savings from avoided damages and insurance reductions.
 * @property {string} roiDescription - A textual description of the return on investment.
 */

/**
 * @typedef {Object} SimulationResult - The complete output object returned by the API.
 * @property {string} id - A unique identifier for this specific simulation run.
 * @property {Object} buildingDesign - A copy of the complete building design used for the simulation (including internal defaults).
 * @property {number} overallResilienceScore - The final resilience score for the target future year.
 * @property {PerformanceTimelineEntry[]} performanceTimeline - An array detailing the building's projected performance over time.
 * @property {string[]} adaptiveRecommendations - An array of specific, actionable recommendations generated by the AI.
 * @property {CostBenefitAnalysis} costBenefitAnalysis - The financial analysis of the recommendations.
 * @property {Date} timestamp - The exact time when the simulation was performed.
 */